# Generated by Django 6.0.1 on 2026-02-02 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(help_text='Thumbs: -1=down, 1=up. Or rating 1-5.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'feedbacks',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='message',
            name='unique_message_sequence_per_conversation',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_300ced_idx',
            old_name='chat_msg_conv_seq_idx',
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('conversation', 'sequence')},
        ),
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chat.message'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['message', '-created_at'], name='chat_feedba_message_c0c882_idx'),
        ),
    ]
